development:
  adapter: postgresql
  database: demo_database
  username: postgres
  password: 123456#
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: demo_database
  username: postgres
  password: 123456#
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: demo_database
  username: postgres
  password: 123456#
  pool: 5
  timeout: 5000